#!/bin/bash
sudo apt-get install libpq-dev g++ gcc build-essential libpng-dev zlib1g-dev bison flex 
sudo apt-get install openbsd-inetd postgresql-server-dev-all postgresql-contrib libjansson-dev zlib1g-dev
sudo apt-get update
sudo apt-get upgrade
echo "Dependancies installed"
rm -rf ~/nethack4
cp -r ~/nethack4-4.3-beta2 ~/nethack4
cp ~/nethack4-4.3-beta2/doc/changelog.txt ~/nethack4/doc/

sudo chmod 666 -R ~/nethack4
sudo chmod 777 ~/nethack4/aimake ~/nethack4/scripts/vcs-hooks/git-hooks-post-commit
sudo find ~/nethack4 -type d -exec chmod 755 {} \;
sudo chmod 777 ~/nethack4/libnethack/util/*.sh
sudo find ~/nethack4 -regex ".*\.(sh|pl|bat)$" -exec chmod 777 {} \;

mkdir ~/nethack4/build
cd ~/nethack4/build
../aimake -i ~/nethack4 --without=gui --with=server --with=playfield_utils


